global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'update_jobs'
    file_sd_configs:
      - files:
          - /etc/prometheus/jobs.json
        refresh_interval: 10s

